.TH server 1 "22 de Junio de 2009" "Version 2.0" "Movie Store Server"





.SH NAME
.B "lookup"
Inicia el servidor PaymentLookupServer para consultar la hubicacion de algun PaymentServer.





.SH DESCRIPTION
lookup es el ejecutable correspondiente a PaymentLookupServer. Este servidor permite consultad la hubicacion de un PaymentServer determinado. Se utiliza durante el
proceso de compra de una pelicula.





.SH AUTHOR
Desarrollado por Nicolas Bombau, Carlos Castro y Damian Dome.





.SH SEE ALSO
.B "client"
,
.B "payment"
,
.B "server"