.TH server 1 "22 de Junio de 2009" "Version 2.0" "Movie Store Server"





.SH NAME
.B "payment"
Inicia el servidor PaymentServer para el manejo de los fondos de un usuario.





.SH DESCRIPTION
payment es el ejecutable correspondiente a PaymentServer. Este servidor se utiliza para administrar el balance de cuenta de los usuarios registrados.






.SH CONFIGURACION
Es importate que antes de ejecutar el cliente se configure apropiadamente el archivo
.B "payment.config"
que debe encontrarse en el mismo directorio que el ejecutable
.B "payment"





.SH AUTHOR
Desarrollado por Nicolas Bombau, Carlos Castro y Damian Dome.





.SH SEE ALSO
.B "client"
,
.B "server"
,
.B "lookup"