.TH server 1 "22 de Junio de 2009" "Version 2.0" "Movie Store Server"





.SH NAME
.B "server"
Inicia el servidor MovieStoreServer para la compra de peliculas online.





.SH DESCRIPTION
server es el ejecutable correspondiente a MovieStoreServer. Este servidor permite conectarse a travez del cliente y pedir un listado de peliculas.
Dichas peliculas podran ser compradas y descargadas al disco local donde se este corriendo el cliente.





.SH AUTHOR
Desarrollado por Nicolas Bombau, Carlos Castro y Damian Dome.





.SH SEE ALSO
.B "client"
,
.B "payment"
,
.B "lookup"